#!/usr/bin/env python3
"""
Multi-Robot Navigation Simulation Launch File
Generated by Spatial_Map Pipeline

This launch file:
1. Starts Gazebo with the building world
2. Spawns multiple robots with LiDAR sensors
3. Loads the occupancy map for navigation
4. Starts the network-guided navigation nodes
5. Starts the multi-robot coordinator
"""

import os
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription, ExecuteProcess
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from ament_index_python.packages import get_package_share_directory


def generate_launch_description():
    # Package paths
    pkg_share = get_package_share_directory('spatial_maps')
    ros_gz_sim_share = get_package_share_directory('ros_gz_sim')

    # Launch arguments
    use_sim_time = LaunchConfiguration('use_sim_time', default='true')
    world_file = LaunchConfiguration('world_file',
        default=os.path.join(pkg_share, 'worlds', 'b1f.world'))
    map_file = LaunchConfiguration('map_file',
        default=os.path.join(pkg_share, 'maps', 'B1F.yaml'))

    # Declare arguments
    declare_use_sim_time = DeclareLaunchArgument(
        'use_sim_time',
        default_value='true',
        description='Use simulation time')

    declare_world_file = DeclareLaunchArgument(
        'world_file',
        default_value=os.path.join(pkg_share, 'worlds', 'b1f.world'),
        description='Gazebo world file')

    declare_map_file = DeclareLaunchArgument(
        'map_file',
        default_value=os.path.join(pkg_share, 'maps', 'B1F.yaml'),
        description='Map YAML file')

    # Gz Sim (replaces gzserver + gzclient)
    gz_sim = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(ros_gz_sim_share, 'launch', 'gz_sim.launch.py')
        ),
        launch_arguments={'gz_args': [world_file, ' -r']}.items()
    )

    # Map server
    map_server = Node(
        package='nav2_map_server',
        executable='map_server',
        name='map_server',
        output='screen',
        parameters=[
            {'yaml_filename': map_file},
            {'use_sim_time': use_sim_time}
        ]
    )

    # Lifecycle manager for map server
    lifecycle_manager = Node(
        package='nav2_lifecycle_manager',
        executable='lifecycle_manager',
        name='lifecycle_manager_map',
        output='screen',
        parameters=[
            {'autostart': True},
            {'node_names': ['map_server']}
        ]
    )

    # Robot descriptions and spawners
    robot_nodes = []

    # Robot 1 spawn
    spawn_robot_1 = Node(
        package='ros_gz_sim',
        executable='create',
        name='spawn_robot_1',
        output='screen',
        arguments=[
            '-name', 'robot_1',
            '-x', '5.0',
            '-y', '5.0',
            '-z', '0.1',
            '-Y', '0.0',
            '-topic', '/robot_1/robot_description'
        ]
    )
    robot_nodes.append(spawn_robot_1)

    # Robot 2 spawn
    spawn_robot_2 = Node(
        package='ros_gz_sim',
        executable='create',
        name='spawn_robot_2',
        output='screen',
        arguments=[
            '-name', 'robot_2',
            '-x', '15.0',
            '-y', '5.0',
            '-z', '0.1',
            '-Y', '0.0',
            '-topic', '/robot_2/robot_description'
        ]
    )
    robot_nodes.append(spawn_robot_2)

    # Robot 3 spawn
    spawn_robot_3 = Node(
        package='ros_gz_sim',
        executable='create',
        name='spawn_robot_3',
        output='screen',
        arguments=[
            '-name', 'robot_3',
            '-x', '25.0',
            '-y', '5.0',
            '-z', '0.1',
            '-Y', '0.0',
            '-topic', '/robot_3/robot_description'
        ]
    )
    robot_nodes.append(spawn_robot_3)

    return LaunchDescription([
        declare_use_sim_time,
        declare_world_file,
        declare_map_file,
        gz_sim,
        map_server,
        lifecycle_manager,
    ] + robot_nodes)
