#!/usr/bin/env python3
"""
Export Gazebo wall geometry from a Spatial_Map pipeline floor GLB.

The pipeline writes entity/glb/floor_<F>.glb and grid/<F>.pgm in the same UCS
frame (metres), so the only conversion needed is glTF Y-up to Gazebo Z-up.
No XY offset is applied: place the mesh at world pose (0, 0, z) and it lands
on the occupancy map directly.  Z is shifted so the lowest IfcWall vertex sits
at z = 0.

Only structural obstacle classes are kept (IfcWall and IfcColumn by default).
IfcSpace volumes and closed IfcDoor panels are left out because they seal
rooms that the occupancy map treats as reachable.

If --yaml is given, the wall cross-section at --check-height above the floor
is compared with the map's occupied cells and the agreement is printed.  The
script exits non-zero when agreement falls below --min-agreement.

Usage:
    python3 glb_to_wall_mesh.py \
        --glb    path/to/floor_1F.glb \
        --output path/to/floor_1F_walls_only.obj \
        [--yaml path/to/1F.yaml] [--classes IfcWall IfcColumn] \
        [--check-height 0.5] [--min-agreement 95]

Requires trimesh.  Offline tool only; nothing at runtime depends on it.
"""

import argparse
import os
import sys

import numpy as np
import trimesh
import yaml
from scipy import ndimage

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pgm_to_sdf_walls import load_pgm  # noqa: E402

# glTF is Y-up with -Z pointing north; Gazebo is Z-up.  (x, y, z) -> (x, -z, y)
Y_UP_TO_Z_UP = np.array([[1, 0, 0, 0],
                         [0, 0, -1, 0],
                         [0, 1, 0, 0],
                         [0, 0, 0, 1]], dtype=float)


# ---------------------------------------------------------------------------
# GLB extraction
# ---------------------------------------------------------------------------

def extract_classes(glb_path: str, classes):
    """Return {ifc_class: [mesh, ...]} in Z-up UCS metres for the given classes."""
    scene = trimesh.load(glb_path, force='scene')
    found = {}
    for node in scene.graph.nodes_geometry:
        ifc_class = node.split('_')[0]
        if ifc_class not in classes:
            continue
        transform, geom_name = scene.graph[node]
        mesh = scene.geometry[geom_name].copy()
        mesh.apply_transform(transform)
        mesh.apply_transform(Y_UP_TO_Z_UP)
        found.setdefault(ifc_class, []).append(mesh)
    return found


def write_obj(mesh, obj_path: str, glb_path: str, classes, z_shift: float):
    mtl_name = os.path.splitext(os.path.basename(obj_path))[0] + '.mtl'
    with open(os.path.join(os.path.dirname(obj_path) or '.', mtl_name), 'w') as f:
        f.write('# Grey wall material\n'
                'newmtl grey_wall\n'
                'Ka 0.35 0.35 0.35\n'
                'Kd 0.50 0.50 0.50\n'
                'Ks 0.05 0.05 0.05\n'
                'Ns 10.0\n'
                'illum 2\n')
    with open(obj_path, 'w') as f:
        f.write(f'# Generated by glb_to_wall_mesh.py from {os.path.basename(glb_path)}\n')
        f.write(f'# Classes: {" ".join(classes)}\n')
        f.write('# Frame: pipeline UCS metres, Z-up, same XY frame as the occupancy map\n')
        f.write(f'# Z shifted by {z_shift:+.4f} m so the wall base is at z = 0\n')
        f.write(f'mtllib {mtl_name}\n')
        f.write('usemtl grey_wall\n')
        for v in mesh.vertices:
            f.write(f'v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n')
        for face in mesh.faces + 1:
            f.write(f'f {face[0]} {face[1]} {face[2]}\n')


# ---------------------------------------------------------------------------
# Alignment check against the occupancy map
# ---------------------------------------------------------------------------

def check_alignment(mesh, yaml_path: str, height: float, step: float = 0.02):
    """Distance from each wall cross-section sample to the nearest occupied cell."""
    with open(yaml_path) as f:
        meta = yaml.safe_load(f)
    pgm_path = meta['image']
    if not os.path.isabs(pgm_path):
        pgm_path = os.path.join(os.path.dirname(yaml_path), pgm_path)
    arr, W, H, _ = load_pgm(pgm_path)
    res = float(meta['resolution'])
    ox, oy = float(meta['origin'][0]), float(meta['origin'][1])

    occ_prob = arr.astype(float) / 255.0 if meta.get('negate', 0) else (255.0 - arr) / 255.0
    occupied = occ_prob > float(meta['occupied_thresh'])
    dist = ndimage.distance_transform_edt(~occupied) * res

    segs = trimesh.intersections.mesh_plane(mesh, [0, 0, 1], [0, 0, height])
    if len(segs) == 0:
        raise RuntimeError(f'No wall geometry at z = {height:.2f} m')
    a, b = segs[:, 0, :2], segs[:, 1, :2]
    n = np.maximum(1, (np.linalg.norm(b - a, axis=1) / step).astype(int))
    t = np.concatenate([np.linspace(0, 1, k + 1) for k in n])
    idx = np.repeat(np.arange(len(segs)), n + 1)
    pts = a[idx] + (b - a)[idx] * t[:, None]

    rows = (H - 1 - np.floor((pts[:, 1] - oy) / res)).astype(int)
    cols = np.floor((pts[:, 0] - ox) / res).astype(int)
    inside = (rows >= 0) & (rows < H) & (cols >= 0) & (cols < W)
    d = dist[rows[inside], cols[inside]]
    return {
        'samples': int(inside.sum()),
        'outside_map': int((~inside).sum()),
        'median': float(np.median(d)),
        'p90': float(np.percentile(d, 90)),
        'within_3px': float(np.mean(d <= 3 * res) * 100.0),
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--glb',     required=True, help='Pipeline floor GLB (entity/glb/floor_<F>.glb)')
    p.add_argument('--output',  required=True, help='Output OBJ path (MTL written alongside)')
    p.add_argument('--yaml',    help='Map YAML to check alignment against')
    p.add_argument('--classes', nargs='+', default=['IfcWall', 'IfcColumn'])
    p.add_argument('--check-height',  type=float, default=0.5,
                   help='Slice height above the wall base for the alignment check (m)')
    p.add_argument('--min-agreement', type=float, default=95.0,
                   help='Minimum %% of slice samples within 3 px of an occupied cell')
    args = p.parse_args()

    found = extract_classes(args.glb, set(args.classes))
    if 'IfcWall' not in found:
        sys.exit(f'No IfcWall geometry in {args.glb}')
    for c in args.classes:
        meshes = found.get(c, [])
        print(f'  {c:12s} {len(meshes):4d} elements, {sum(len(m.faces) for m in meshes):6d} faces')

    z_shift = -min(m.bounds[0, 2] for m in found['IfcWall'])
    mesh = trimesh.util.concatenate([m for ms in found.values() for m in ms])
    mesh.apply_translation([0.0, 0.0, z_shift])
    write_obj(mesh, args.output, args.glb, args.classes, z_shift)
    lo, hi = mesh.bounds
    print(f'Wrote {args.output}: {len(mesh.faces)} faces, '
          f'x {lo[0]:.3f}..{hi[0]:.3f}  y {lo[1]:.3f}..{hi[1]:.3f}  z {lo[2]:.3f}..{hi[2]:.3f}')

    if args.yaml:
        r = check_alignment(mesh, args.yaml, args.check_height)
        print(f'Alignment vs {os.path.basename(args.yaml)} at z = {args.check_height:.2f} m: '
              f'{r["within_3px"]:.1f}% of {r["samples"]} samples within 3 px, '
              f'median {r["median"]:.3f} m, p90 {r["p90"]:.3f} m, '
              f'{r["outside_map"]} samples outside the map')
        if r['within_3px'] < args.min_agreement:
            sys.exit(f'Alignment below {args.min_agreement:.0f}%: check the GLB and map belong together')


if __name__ == '__main__':
    main()
